config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dogs, only: [:index, :show, :new, :create] do
  resources :bookings, only: [:new, :create, :show, :destroy]
  end
  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dog

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :telephone])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :telephone])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @booking = current_user.bookings
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new(bookings_params)

    @booking.dog = @dog
    @booking.user = current_user
    if @booking.save!
      redirect_to dog_booking_path(@dog, @booking)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def new
    @booking = Booking.new
    @dog = Dog.find(params[:dog_id])
  end

  def show
    @booking = Booking.find(params[:id])
    # # @array_single_dog = []
    # # @array_single_dog << @booking.dog
    # @markers = @booking.dog.geocode.map do |dog|
    #   {
    #     lat: dog.latitude,
    #     lng: dog.longitude,

    #     info_window: render_to_string(partial: "info_window", locals: {dog: dog})
    #   }
    # end
    @dog = Dog.find(params[:dog_id])
    @markers = [{ lat: @dog.geocode[0], lng: @dog.geocode[1] }]
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to dog_path, status: :see_other
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

# @list = List.find(params[:list_id])
#     @bookmark = Bookmark.new(bookmark_params)
#     @bookmark.list = @list
#     if @bookmark.save
#       redirect_to list_path(@list)
#     else
#       render 'new', status: :unprocessable_entity
#     end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
    @markers = @dogs.geocoded.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude,
        info_window: render_to_string(partial: "info_window", locals: {dog: dog})
      }
    end
  end

  def show
    @dog = Dog.find(params[:id])
    @markers = [{lat: @dog.geocode[0], lng: @dog.geocode[1]}]
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dogs_params)
    @dog.user = current_user
    @dog.save!
    redirect_to dogs_path
  end

  private

  def dogs_params
    params.require(:dog).permit(:name, :description, :age, :location, :photo, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @dogs = Dog.all.sample(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="card-container">
    <% @booking.each do |book| %>
      <div class="card">
        <% if book.dog.photo.attached?  %>
          <%= cl_image_tag book.dog.photo.key, class: "photo" %>
        <%else %>
          <img class="photo" src="<%= book.dog.picture %>" alt="">
        <% end %>
        <div class="text">
        <h2 class ="dog-name"> <%= book.dog.name %></h2>
        <div class="scroll-text">
          <p>Start-date: <%= book.start_date %></p>
          <p>End-date: <%= book.end_date %></p>
          <h3 class="dog-price"><%= book.dog.price %>€/day</h3>
        </div>
        </div>
      </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%# <%= simple_form_for [@dog, @booking] do |f| %>

  <%# <div class="form-inputs"> %>
    <%# <%= f.input :start_date %>
    <%# <%= f.input :end_date %>
  <%# </div> %>

<head>
</head>
  <div class="banner-newbooking">
    <div class="container-container-inputform">
      <div class="container-inputform">
        <div id='dog-booking-dates' data-unavailable="<%= @dog.unavailable_dates.to_json %>">
            <% if current_user != @dog.user_id  %>
          <%= simple_form_for ([@dog, @booking]) do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker", id: "range_start"} %>
                <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker", id: "range_end"} %>
                <%= f.button :submit, "Submit", class: "btn btn-primary" %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>



  <%# <div class="form-actions"> %>
    <%# <%= f.button :submit %>
  <%# </div> %>
<%# <% end %>

app/views/bookings/show.html.erb
<h1 class="title1">Congratulations!</h1>
<h1 class="title-bookings">You've just made a booking!</h1>
<div class= "container-booking-body">
  <div class= "booking-dog-name">
    <p>
    Your Doggy - <%= @booking.dog.name %>
    </p>
  </div>
   <% if @booking.dog.photo.attached?  %>
   <%= cl_image_tag @booking.dog.photo.key, class: "photo" %>
    <%else %>
  <img class="photo" src="<%= @booking.dog.picture %>" alt="">
    <% end %>
    <div class="booking-dates">
     <p> You'll have <%=@booking.dog.name%> for the following dates: <%= @booking.start_date %> - <%= @booking.end_date %></p>
    </div>
  <div class="booking-location">
    <p> <h4 class="dog-pickup" >You can pick up <%=@booking.dog.name%> from here! </h4></p>
    <%= @booking.dog.location %>
  </div>
  </div>
  <br>



<br>


  <br>

 <%# <%= link_to "DELETE", dog_booking_path(@booking, @dog),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/dogs/_info_window.html.erb
<h2><%= dog.name %></h2>
<p><%= dog.location %></p>

app/views/dogs/index.html.erb
<html>
<head>
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/components/banner.css">
</head>
<body class="body">
  <div class="cards-map-container">
    <div class="card-container">
        <% @dogs.each do |dog| %>
          <%= link_to  dog_path(dog.id) do %>
            <div class="card">
              <% if dog.photo.attached?  %>
                <%= cl_image_tag dog.photo.key, class: "photo" %>
                <%else %>
                <img class="photo" src="<%= dog.picture %>" alt="">
              <% end %>
              <div class = "text">
                <h2 class ="dog-name"> <%= dog.name %></h2>
                <div class ="scroll-text">
                  <p>Age: <%= dog.age %></p>
                  <p>Location: <%= dog.location %></p>
                  <p><%= dog.description %></p>
                </div>
              </div>
              <h3 class="dog-price"><%= dog.price %>€/day</h3>
            </div>
          <% end %>
        <% end %>
    </div>
    <div class ="map-container">
      <div style="width: 100%; height: 600px; border-radius: 10px"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</body>
</html>

<%# <%= link_to dog.name, dog_path(dog.id) %>

app/views/dogs/new.html.erb
<div class="banner-createdog">
  <%= simple_form_for(@dog) do |f| %>
    <div class="container-inputform">
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :age %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :photo, as: :file %>
        <%= f.input :price %>
      </div>

      <div class="button">
        <%= f.button :submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/dogs/show.html.erb
<div class="banner">
  <div class="show-container">


 <% if @dog.photo.attached?  %>
   <%= cl_image_tag @dog.photo.key, class: "photo" %>
    <%else %>
  <img class="photo" src="<%= @dog.picture %>" alt="">
    <% end %>
  <div class="info">
      <h2>
        <%= @dog.name %>
      </h2>

      <h5>Age:</h5>
      <p><%= @dog.age %></p>

      <h5>Location:</h5><p><%= @dog.location %></p>

      <h5>Description:</h5>
      <p>
        <%= @dog.description %>
      </p>
    <h5>Price:</h5>
      <p>
        <%= @dog.price %>€ per day
      </p>
      <p class="button">
        <%= link_to "Book Me", new_dog_booking_path(@dog) %>
      </p>
    </div>
  </div>
</div>


<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocalDoggy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>



  <body>
   <%= render "shared/navbar" %>
   <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<body>
<div class="banner-home">
      <%= image_tag "localdoggywhite.png", class: "logo-doggy-logo"%>
  <div class="container-welcome">
    <div>
      <%# <img class="local-logo" src="https://www.canva.com/design/DAFKax25kKM/hjGLIs2sPObwrSD2kC3zHg/edit?utm_content=DAFKax25kKM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton" alt=""> %>
      <h1>Welcome to LocalDoggy</h1>
      <h3>Your exciting doggy experience starts today!</h3>
    </div>
  </div>
</div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <div><%= image_tag "localdoggywhite.png" %>
      </div>
    <% end %>

   <div id="nav-title"><%= LocalDoggy %>
   </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path(@dogs) %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path(@booking) %>
          </li>
          <li class="nav-item">
            <%= link_to 'Create dog', new_dog_path(@dog) %>
          </li>
          <li class="nav-item">
            <%= link_to 'Show Dogs', dogs_path(@dogs) %>
          </li>
          <li class="nav-item dropdown" style="margin-top: 8px;">
            <%= image_tag "https://freepikpsd.com/file/2019/10/white-paw-print-png-Transparent-Images.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
             <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
          <li class="nav-item" style="color: white">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>